### ISSUE TITLE
idiot

### ISSUE THREAD

**Issue by Dragonov12333** [kirtzyx/TargetPlay-Grabber#3]
Are u a fucking idiot, uploading a github page without any type source, links to get it. dumbass

**Comment by Dragonov12333** [comment]
like who tf will acctually trust ur fucking project that u will give as an exe not a source code lmfao, github isnt for advertising lol.

**Comment by kirtzyx** [comment]
cope retard

**Comment by kirtzyx** [comment]
and it works through a discord bot u retard
